# Generated by Django 3.1.14 on 2024-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='price',
        ),
        migrations.RemoveField(
            model_name='song',
            name='type',
        ),
        migrations.AddField(
            model_name='song',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
    ]
