# Generated by Django 3.1.14 on 2024-02-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240204_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playtime',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Playtime in seconds'),
        ),
    ]
