# Generated by Django 3.1.14 on 2024-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240204_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playtime',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Playtime'),
        ),
    ]
