# Generated by Django 3.1.14 on 2024-02-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playbackhistory_userartist_usergenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playtime',
        ),
    ]
