# Generated by Django 3.1.14 on 2024-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_song_playtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playtime',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Playtime'),
        ),
    ]
