# Generated by Django 3.1.14 on 2024-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_song_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playtime',
            field=models.CharField(default=0.0, editable=False, max_length=200, verbose_name='Playtime'),
        ),
    ]
